# Created by trellis-cli vcanary
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  incrivelhistoria.com.br:
    site_hosts:
    - canonical: incrivelhistoria.com.br
      redirects:
      - www.incrivelhistoria.com.br
    local_path: ../site
    branch: master
    repo: git@github.com:dsemblano/incrivelhistoria.com.br.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
    xmlrpc:
      enabled: false
